### PR TITLE
sync reviews and status with salesforce

### PR DESCRIPTION
**Pull request by mwharrison**

### CODE REVIEW

**Comment by mwharrison** [comment]
@RoyEJohnson - How all this partner stuff is working. Let me know if anything needs tweaking/clarification.

**Endpoint: /apps/cms/api/salesforce/reviews/**
Submit a _POST_ request to create a new review.
```
{
        "partner": 327,
        "review": "Updated review text",
        "rating": 4,
        "submitted_by_name": "Professor Green",
        "submitted_by_account_id": 2,
    }
```

Submit a _PATCH_ request with the review id to update a review. (You only need the ID and the updated data in the request)
```
{
        "id": 6,
        "partner": 327,
        "review": "Updated review text",
        "rating": 4,
        "submitted_by_name": "Professor Green",
        "submitted_by_account_id": 2,
    }
```

After a creation/update, the review is no longer visible in the API, it reenters the approval queue. Only approved reviews appear in the API. Let me know if this is an issue, you can take the show/hide control by looking at the review `status` field (currently not in the API).

**Endpoint: /apps/cms/api/salesforce/partners/**
Review average rating and count are included on the list view.

**Endpoint: /apps/cms/api/salesforce/partners/[id]**
Includes the individual reviews (approved only) and partner average and review count.

**Comment by RoyEJohnson** [comment]
> After a creation/update, the review is no longer visible in the API, it reenters the approval queue. Only approved reviews appear in the API. Let me know if this is an issue, you can take the show/hide control by looking at the review `status` field (currently not in the API).

Users need to be able to see and re-edit their own pending reviews. So I think it needs the status field.

**Review by RoyEJohnson — CHANGES_REQUESTED** [review]
Users need to be able to see their own un-approved reviews.

**Comment by mwharrison** [comment]
@RoyEJohnson updated to include all reviews and updated the documentation to reflect that you can query by user id

**Review by RoyEJohnson — APPROVED** [review]

**Pull request merged**
