### PR TITLE
Impact page tweaks

### PR DESCRIPTION
**Pull request by mwharrison**

### CODE REVIEW

**Comment by RoyEJohnson** [comment]
On the default entries for the page, Reach section, don't put the `>` on the read more link text.

**Comment by RoyEJohnson** [comment]
Typo: "embeded_video" should be "embedded_video" (in making_a_difference.stories.type)

**Comment by RoyEJohnson** [comment]
The graph in the disruption section is just an image. All the captions are part of the image, not separate.

**Comment by RoyEJohnson** [comment]
Giving section needs:

- nonprofit_statement
- annual_report_link_text
- annual_report_link_href

**Comment by RoyEJohnson** [comment]
In the Giving section, when you create the default page, link and link text values are swapped.

**Comment by mwharrison** [comment]
@RoyEJohnson this should be ready for review

**Review by RoyEJohnson — APPROVED** [review]
Looks good to me. Let's see how it flies.

**Pull request merged**
